name: Pull Request Updator

on:
  workflow_call:
    secrets:
      token:
        required: true
jobs:
  update-pr:
    name: Update PR
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/pr-labeler.yml
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
      - uses: tzkhan/pr-update-action@v2
        with:
          repo-token: "${{ secrets.token }}"
          base-branch-regex: '[a-z\d-_.\\/]+'
          head-branch-regex: 'sc-\d+'
          title-template: '[%headbranch%] '