name: Pull Request Updator

on:
  workflow_call:
    secrets:
      token:
        required: true
jobs:
  update_pr_title:
    name: Add Shortcut No to PR title
    runs-on: ubuntu-latest
    steps:
      - uses: tzkhan/pr-update-action@v2
        with:
          repo-token: "${{ secrets.token }}"
          base-branch-regex: '[a-z\d-_.\\/]+'
          head-branch-regex: 'sc-\d+'
          title-template: '[%headbranch%] '